version: 1
accounts:
- name: Alice
  coins:
  - 20000token
  - 20000foocoin
  - 200000000stake

- name: Bob
  coins:
  - 10000token
  - 10000foocoin
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: Bob
  coins:
  - 10token
  - 10foocoin
  name: Alice
  coins:
  - 10token
  - 10foocoin
validators:
- name: Alice
  bonded: 100000000stake
