version: 1
accounts:
- name: Alice
  coins:
  - 3000000foocoin
  - 300000token
  - 200000000stake

- name: Bob
  coins:
  - 100000foocoin
  - 100000token
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: Bob
  coins:
  - 10token
  - 10foocoin
validators:
- name: Alice
  bonded: 100000000stake
