version: 1
accounts:
- name: Alice
  coins:
  - 300000000000foocoin
  - 300000000000token
  - 100000000000frog
  - 200000000000stake

- name: Bob
  coins:
  - 100000000000foocoin
  - 100000000000token
  - 100000000000frog
  - 100000000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: Bob
  coins:
  - 10token
  - 10foocoin
validators:
- name: Alice
  bonded: 100000000stake
  app:
    api:
      address: :1318
    grpc:
      address: :9092
    grpc-web:
      address: :9093
  config:
    p2p:
      laddr: :26658
    rpc:
      laddr: :26659
      pprof_laddr: :6061
