// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: frogchain/amm/pool.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Pool struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// pool params for swap and exit fees
	PoolParam PoolParam `protobuf:"bytes,2,opt,name=poolParam,proto3" json:"poolParam"`
	// assets in the pool
	PoolAssets   []types.Coin                             `protobuf:"bytes,3,rep,name=poolAssets,proto3" json:"poolAssets"`
	AssetWeights []github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,rep,name=assetWeights,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"assetWeights"`
	// LP token
	ShareToken types.Coin `protobuf:"bytes,5,opt,name=shareToken,proto3" json:"shareToken"`
	// min liquidity is the minimum amount of share token to maintain the pool
	MinimumLiquidity github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=minimumLiquidity,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"minimumLiquidity"`
	// Pool activate state
	IsActivated bool `protobuf:"varint,7,opt,name=isActivated,proto3" json:"isActivated,omitempty"`
}

func (m *Pool) Reset()         { *m = Pool{} }
func (m *Pool) String() string { return proto.CompactTextString(m) }
func (*Pool) ProtoMessage()    {}
func (*Pool) Descriptor() ([]byte, []int) {
	return fileDescriptor_b59f92a00a9fe694, []int{0}
}
func (m *Pool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Pool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Pool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Pool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pool.Merge(m, src)
}
func (m *Pool) XXX_Size() int {
	return m.Size()
}
func (m *Pool) XXX_DiscardUnknown() {
	xxx_messageInfo_Pool.DiscardUnknown(m)
}

var xxx_messageInfo_Pool proto.InternalMessageInfo

func (m *Pool) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pool) GetPoolParam() PoolParam {
	if m != nil {
		return m.PoolParam
	}
	return PoolParam{}
}

func (m *Pool) GetPoolAssets() []types.Coin {
	if m != nil {
		return m.PoolAssets
	}
	return nil
}

func (m *Pool) GetShareToken() types.Coin {
	if m != nil {
		return m.ShareToken
	}
	return types.Coin{}
}

func (m *Pool) GetIsActivated() bool {
	if m != nil {
		return m.IsActivated
	}
	return false
}

func init() {
	proto.RegisterType((*Pool)(nil), "frogchain.amm.Pool")
}

func init() { proto.RegisterFile("frogchain/amm/pool.proto", fileDescriptor_b59f92a00a9fe694) }

var fileDescriptor_b59f92a00a9fe694 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x6b, 0xdb, 0x30,
	0x14, 0xc7, 0xad, 0xd8, 0xcb, 0x16, 0x65, 0x1b, 0xc3, 0x6c, 0xa0, 0xed, 0xe0, 0x98, 0x1d, 0x86,
	0x2f, 0x93, 0x48, 0x76, 0x1d, 0x8c, 0x64, 0x3b, 0xee, 0x10, 0x4c, 0xa1, 0x90, 0x4b, 0x91, 0x6d,
	0xd5, 0x16, 0x89, 0x2c, 0xd7, 0x52, 0x42, 0xf3, 0x2d, 0xfa, 0x31, 0xfa, 0x51, 0x72, 0xcc, 0xb1,
	0xf4, 0x10, 0x4a, 0xf2, 0x45, 0x8a, 0x1c, 0xa7, 0x49, 0x48, 0xa1, 0xd0, 0x93, 0x9f, 0xf5, 0x7f,
	0xff, 0xf7, 0x7e, 0x4f, 0x7a, 0x10, 0x5d, 0x96, 0x32, 0x8d, 0x33, 0xca, 0x73, 0x42, 0x85, 0x20,
	0x85, 0x94, 0x13, 0x5c, 0x94, 0x52, 0x4b, 0xf7, 0xc3, 0x93, 0x82, 0xa9, 0x10, 0xdf, 0xbc, 0xd3,
	0xc4, 0x8b, 0x82, 0x96, 0x54, 0x6c, 0xd3, 0x9f, 0xd5, 0xb5, 0x1c, 0xb3, 0xbc, 0xd6, 0x3f, 0xa7,
	0x32, 0x95, 0x55, 0x48, 0x4c, 0xb4, 0x73, 0xc5, 0x52, 0x09, 0xa9, 0x48, 0x44, 0x15, 0x23, 0xb3,
	0x6e, 0xc4, 0x34, 0xed, 0x92, 0x58, 0xf2, 0xda, 0xf5, 0xfd, 0xd6, 0x86, 0xce, 0x50, 0xca, 0x89,
	0xfb, 0x11, 0x36, 0x78, 0x82, 0x80, 0x0f, 0x02, 0x27, 0x6c, 0xf0, 0xc4, 0xfd, 0x0d, 0x5b, 0xa6,
	0xc5, 0xd0, 0x10, 0xa0, 0x86, 0x0f, 0x82, 0x76, 0x0f, 0xe1, 0x23, 0x62, 0x3c, 0xdc, 0xe9, 0x03,
	0x67, 0xb1, 0xea, 0x58, 0xe1, 0xde, 0xe0, 0xfe, 0x81, 0xd0, 0xfc, 0xf4, 0x95, 0x62, 0x5a, 0x21,
	0xdb, 0xb7, 0x83, 0x76, 0xef, 0x2b, 0xde, 0xb2, 0x60, 0xc3, 0x82, 0x6b, 0x16, 0xfc, 0x57, 0xf2,
	0xbc, 0xf6, 0x1f, 0x58, 0xdc, 0x10, 0xbe, 0xa7, 0x26, 0x3a, 0x67, 0x3c, 0xcd, 0xb4, 0x42, 0x8e,
	0x6f, 0x07, 0xad, 0x01, 0x36, 0x79, 0xf7, 0xab, 0xce, 0x8f, 0x94, 0xeb, 0x6c, 0x1a, 0xe1, 0x58,
	0x0a, 0x52, 0x0f, 0xb8, 0xfd, 0xfc, 0x54, 0xc9, 0x98, 0xe8, 0x79, 0xc1, 0x14, 0xfe, 0xc7, 0xe2,
	0xf0, 0xa8, 0x86, 0x81, 0x52, 0x19, 0x2d, 0xd9, 0x99, 0xb9, 0x35, 0xf4, 0xa6, 0x9a, 0xe9, 0x65,
	0xa8, 0xbd, 0xc5, 0x1d, 0xc1, 0x4f, 0x82, 0xe7, 0x5c, 0x4c, 0xc5, 0x7f, 0x7e, 0x35, 0xe5, 0x09,
	0xd7, 0x73, 0xd4, 0xf4, 0xc1, 0x2b, 0xc0, 0x4e, 0xea, 0xb8, 0x3e, 0x6c, 0x73, 0xd5, 0x8f, 0x35,
	0x9f, 0x51, 0xcd, 0x12, 0xf4, 0xd6, 0x07, 0xc1, 0xbb, 0xf0, 0xf0, 0x68, 0x40, 0x16, 0x6b, 0x0f,
	0x2c, 0xd7, 0x1e, 0x78, 0x58, 0x7b, 0xe0, 0x66, 0xe3, 0x59, 0xcb, 0x8d, 0x67, 0xdd, 0x6d, 0x3c,
	0x6b, 0xf4, 0x65, 0xbf, 0x1a, 0xd7, 0xd5, 0x72, 0x54, 0x8d, 0xa2, 0x66, 0xf5, 0xc4, 0xbf, 0x1e,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xbe, 0xb6, 0x52, 0x83, 0x02, 0x00, 0x00,
}

func (m *Pool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Pool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Pool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsActivated {
		i--
		if m.IsActivated {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	{
		size := m.MinimumLiquidity.Size()
		i -= size
		if _, err := m.MinimumLiquidity.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPool(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.ShareToken.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPool(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.AssetWeights) > 0 {
		for iNdEx := len(m.AssetWeights) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.AssetWeights[iNdEx].Size()
				i -= size
				if _, err := m.AssetWeights[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintPool(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.PoolAssets) > 0 {
		for iNdEx := len(m.PoolAssets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PoolAssets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPool(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size, err := m.PoolParam.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPool(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Id != 0 {
		i = encodeVarintPool(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPool(dAtA []byte, offset int, v uint64) int {
	offset -= sovPool(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Pool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovPool(uint64(m.Id))
	}
	l = m.PoolParam.Size()
	n += 1 + l + sovPool(uint64(l))
	if len(m.PoolAssets) > 0 {
		for _, e := range m.PoolAssets {
			l = e.Size()
			n += 1 + l + sovPool(uint64(l))
		}
	}
	if len(m.AssetWeights) > 0 {
		for _, e := range m.AssetWeights {
			l = e.Size()
			n += 1 + l + sovPool(uint64(l))
		}
	}
	l = m.ShareToken.Size()
	n += 1 + l + sovPool(uint64(l))
	l = m.MinimumLiquidity.Size()
	n += 1 + l + sovPool(uint64(l))
	if m.IsActivated {
		n += 2
	}
	return n
}

func sovPool(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPool(x uint64) (n int) {
	return sovPool(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Pool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Pool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Pool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolParam", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PoolParam.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolAssets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolAssets = append(m.PoolAssets, types.Coin{})
			if err := m.PoolAssets[len(m.PoolAssets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetWeights", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Dec
			m.AssetWeights = append(m.AssetWeights, v)
			if err := m.AssetWeights[len(m.AssetWeights)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShareToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ShareToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumLiquidity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinimumLiquidity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsActivated", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsActivated = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPool(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPool
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPool
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPool
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPool
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPool        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPool          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPool = fmt.Errorf("proto: unexpected end of group")
)
