// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: frogchain/amm/pool_param.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PoolParam struct {
	SwapFee uint64 `protobuf:"varint,1,opt,name=swapFee,proto3" json:"swapFee,omitempty"`
	ExitFee uint64 `protobuf:"varint,2,opt,name=exitFee,proto3" json:"exitFee,omitempty"`
}

func (m *PoolParam) Reset()         { *m = PoolParam{} }
func (m *PoolParam) String() string { return proto.CompactTextString(m) }
func (*PoolParam) ProtoMessage()    {}
func (*PoolParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_01cedd9805c43f80, []int{0}
}
func (m *PoolParam) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoolParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoolParam.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoolParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolParam.Merge(m, src)
}
func (m *PoolParam) XXX_Size() int {
	return m.Size()
}
func (m *PoolParam) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolParam.DiscardUnknown(m)
}

var xxx_messageInfo_PoolParam proto.InternalMessageInfo

func (m *PoolParam) GetSwapFee() uint64 {
	if m != nil {
		return m.SwapFee
	}
	return 0
}

func (m *PoolParam) GetExitFee() uint64 {
	if m != nil {
		return m.ExitFee
	}
	return 0
}

func init() {
	proto.RegisterType((*PoolParam)(nil), "frogchain.amm.PoolParam")
}

func init() { proto.RegisterFile("frogchain/amm/pool_param.proto", fileDescriptor_01cedd9805c43f80) }

var fileDescriptor_01cedd9805c43f80 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4b, 0x2b, 0xca, 0x4f,
	0x4f, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x4f, 0xcc, 0xcd, 0xd5, 0x2f, 0xc8, 0xcf, 0xcf, 0x89, 0x2f,
	0x48, 0x2c, 0x4a, 0xcc, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x85, 0xcb, 0xeb, 0x25,
	0xe6, 0xe6, 0x2a, 0xd9, 0x73, 0x71, 0x06, 0xe4, 0xe7, 0xe7, 0x04, 0x80, 0x54, 0x08, 0x49, 0x70,
	0xb1, 0x17, 0x97, 0x27, 0x16, 0xb8, 0xa5, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0xc1,
	0xb8, 0x20, 0x99, 0xd4, 0x8a, 0xcc, 0x12, 0x90, 0x0c, 0x13, 0x44, 0x06, 0xca, 0x75, 0xd2, 0x3f,
	0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63,
	0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86, 0x28, 0x51, 0x84, 0x4b, 0x2a, 0xc0, 0x6e,
	0x29, 0xa9, 0x2c, 0x48, 0x2d, 0x4e, 0x62, 0x03, 0xbb, 0xc3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x4b, 0x82, 0x2c, 0x0b, 0xa9, 0x00, 0x00, 0x00,
}

func (m *PoolParam) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoolParam) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoolParam) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExitFee != 0 {
		i = encodeVarintPoolParam(dAtA, i, uint64(m.ExitFee))
		i--
		dAtA[i] = 0x10
	}
	if m.SwapFee != 0 {
		i = encodeVarintPoolParam(dAtA, i, uint64(m.SwapFee))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPoolParam(dAtA []byte, offset int, v uint64) int {
	offset -= sovPoolParam(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PoolParam) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SwapFee != 0 {
		n += 1 + sovPoolParam(uint64(m.SwapFee))
	}
	if m.ExitFee != 0 {
		n += 1 + sovPoolParam(uint64(m.ExitFee))
	}
	return n
}

func sovPoolParam(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPoolParam(x uint64) (n int) {
	return sovPoolParam(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PoolParam) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoolParam
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoolParam: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoolParam: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapFee", wireType)
			}
			m.SwapFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolParam
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SwapFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExitFee", wireType)
			}
			m.ExitFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolParam
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExitFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPoolParam(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPoolParam
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPoolParam(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPoolParam
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoolParam
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoolParam
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPoolParam
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPoolParam
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPoolParam
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPoolParam        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPoolParam          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPoolParam = fmt.Errorf("proto: unexpected end of group")
)
