// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: frogchain/investibc/params.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	AdminAccount                    string     `protobuf:"bytes,1,opt,name=adminAccount,proto3" json:"adminAccount,omitempty" yaml:"admin_account"`
	DepositDenom                    string     `protobuf:"bytes,2,opt,name=depositDenom,proto3" json:"depositDenom,omitempty" yaml:"deposit_denom"`
	CurrentDepositAmount            types.Coin `protobuf:"bytes,3,opt,name=currentDepositAmount,proto3" json:"currentDepositAmount" yaml:"current_deposit_amount"`
	LiquidityDenom                  string     `protobuf:"bytes,4,opt,name=liquidityDenom,proto3" json:"liquidityDenom,omitempty" yaml:"liquidity_denom"`
	CurrentLiquidityAmount          types.Coin `protobuf:"bytes,5,opt,name=currentLiquidityAmount,proto3" json:"currentLiquidityAmount" yaml:"current_liquidity_amount"`
	DepositLastTime                 uint64     `protobuf:"varint,6,opt,name=depositLastTime,proto3" json:"depositLastTime,omitempty"`
	IcaConnectionId                 string     `protobuf:"bytes,7,opt,name=icaConnectionId,proto3" json:"icaConnectionId,omitempty"`
	JoinSwapExactAmountInPacketSent bool       `protobuf:"varint,8,opt,name=joinSwapExactAmountInPacketSent,proto3" json:"joinSwapExactAmountInPacketSent,omitempty"`
	LockTokensPacketSent            bool       `protobuf:"varint,9,opt,name=lockTokensPacketSent,proto3" json:"lockTokensPacketSent,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4c1845c6e797f8b, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAdminAccount() string {
	if m != nil {
		return m.AdminAccount
	}
	return ""
}

func (m *Params) GetDepositDenom() string {
	if m != nil {
		return m.DepositDenom
	}
	return ""
}

func (m *Params) GetCurrentDepositAmount() types.Coin {
	if m != nil {
		return m.CurrentDepositAmount
	}
	return types.Coin{}
}

func (m *Params) GetLiquidityDenom() string {
	if m != nil {
		return m.LiquidityDenom
	}
	return ""
}

func (m *Params) GetCurrentLiquidityAmount() types.Coin {
	if m != nil {
		return m.CurrentLiquidityAmount
	}
	return types.Coin{}
}

func (m *Params) GetDepositLastTime() uint64 {
	if m != nil {
		return m.DepositLastTime
	}
	return 0
}

func (m *Params) GetIcaConnectionId() string {
	if m != nil {
		return m.IcaConnectionId
	}
	return ""
}

func (m *Params) GetJoinSwapExactAmountInPacketSent() bool {
	if m != nil {
		return m.JoinSwapExactAmountInPacketSent
	}
	return false
}

func (m *Params) GetLockTokensPacketSent() bool {
	if m != nil {
		return m.LockTokensPacketSent
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "frogchain.investibc.Params")
}

func init() { proto.RegisterFile("frogchain/investibc/params.proto", fileDescriptor_d4c1845c6e797f8b) }

var fileDescriptor_d4c1845c6e797f8b = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x18, 0x86, 0x13, 0xe8, 0xca, 0x66, 0x10, 0x48, 0xa6, 0x9a, 0x42, 0x11, 0x49, 0x54, 0x09, 0x91,
	0x53, 0xa2, 0x0d, 0x71, 0x99, 0xb8, 0xac, 0x1b, 0x12, 0x93, 0x76, 0x98, 0xb2, 0x9d, 0xb8, 0x54,
	0xae, 0x63, 0x8a, 0x69, 0xed, 0x2f, 0xc4, 0xee, 0x58, 0xf9, 0x15, 0x88, 0x13, 0x47, 0x7e, 0xce,
	0x8e, 0x3b, 0x72, 0xaa, 0x50, 0xfb, 0x0f, 0xfa, 0x0b, 0x50, 0x62, 0xb7, 0x5b, 0xa3, 0x4d, 0xbb,
	0x55, 0xdf, 0xfb, 0x7e, 0xef, 0xf7, 0xbc, 0x55, 0x8c, 0xc2, 0xcf, 0x05, 0x0c, 0xe8, 0x17, 0xc2,
	0x65, 0xc2, 0xe5, 0x39, 0x53, 0x9a, 0xf7, 0x69, 0x92, 0x93, 0x82, 0x08, 0x15, 0xe7, 0x05, 0x68,
	0xc0, 0xcf, 0x57, 0x8e, 0x78, 0xe5, 0x68, 0xb7, 0x06, 0x30, 0x80, 0x4a, 0x4f, 0xca, 0x5f, 0xc6,
	0xda, 0xf6, 0x29, 0x28, 0x01, 0x2a, 0xe9, 0x13, 0xc5, 0x92, 0xf3, 0x9d, 0x3e, 0xd3, 0x64, 0x27,
	0xa1, 0xc0, 0xa5, 0xd1, 0x3b, 0xbf, 0x36, 0x50, 0xf3, 0xa4, 0xca, 0xc6, 0xef, 0xd1, 0x13, 0x92,
	0x09, 0x2e, 0xf7, 0x29, 0x85, 0xb1, 0xd4, 0x9e, 0x1b, 0xba, 0xd1, 0x56, 0xd7, 0x5b, 0x4c, 0x83,
	0xd6, 0x84, 0x88, 0xd1, 0x5e, 0xa7, 0x52, 0x7b, 0xc4, 0xc8, 0x9d, 0x74, 0xcd, 0x5d, 0x6e, 0x67,
	0x2c, 0x07, 0xc5, 0xf5, 0x21, 0x93, 0x20, 0xbc, 0x07, 0xf5, 0x6d, 0xab, 0xf6, 0xb2, 0x52, 0xee,
	0xa4, 0x6b, 0x6e, 0xac, 0x51, 0x8b, 0x8e, 0x8b, 0x82, 0x49, 0x7d, 0x68, 0xc6, 0xfb, 0xa2, 0x62,
	0x78, 0x18, 0xba, 0xd1, 0xe3, 0xdd, 0x17, 0xb1, 0x69, 0x11, 0x97, 0x2d, 0x62, 0xdb, 0x22, 0x3e,
	0x00, 0x2e, 0xbb, 0xaf, 0x2f, 0xa7, 0x81, 0xb3, 0x98, 0x06, 0xaf, 0xcc, 0x11, 0x1b, 0xd2, 0x5b,
	0x1e, 0x23, 0xc2, 0xb0, 0xde, 0x9a, 0x8e, 0xbb, 0xe8, 0xe9, 0x88, 0x7f, 0x1b, 0xf3, 0x8c, 0xeb,
	0x89, 0xa1, 0x6e, 0x54, 0xd4, 0xed, 0xc5, 0x34, 0xd8, 0x36, 0x81, 0x2b, 0x7d, 0xc9, 0x5d, 0xdb,
	0xc0, 0x3f, 0xd0, 0xb6, 0xcd, 0x3e, 0x5e, 0x0a, 0x96, 0x7d, 0xe3, 0x3e, 0xf6, 0x37, 0x96, 0x3d,
	0x58, 0x67, 0xbf, 0x3e, 0xb9, 0xa4, 0xbf, 0xe3, 0x02, 0x8e, 0xd0, 0x33, 0x5b, 0xf4, 0x98, 0x28,
	0x7d, 0xc6, 0x05, 0xf3, 0x9a, 0xa1, 0x1b, 0x35, 0xd2, 0xfa, 0xb8, 0x74, 0x72, 0x4a, 0x0e, 0x40,
	0x4a, 0x46, 0x35, 0x07, 0x79, 0x94, 0x79, 0x8f, 0xca, 0xaa, 0x69, 0x7d, 0x8c, 0x3f, 0xa2, 0xe0,
	0x2b, 0x70, 0x79, 0xfa, 0x9d, 0xe4, 0x1f, 0x2e, 0x08, 0xb5, 0x7f, 0xd5, 0x91, 0x3c, 0x21, 0x74,
	0xc8, 0xf4, 0x29, 0x93, 0xda, 0xdb, 0x0c, 0xdd, 0x68, 0x33, 0xbd, 0xcf, 0x86, 0x77, 0x51, 0x6b,
	0x04, 0x74, 0x78, 0x06, 0x43, 0x26, 0xd5, 0x8d, 0xf5, 0xad, 0x6a, 0xfd, 0x56, 0x6d, 0xaf, 0xf1,
	0xfb, 0x4f, 0xe0, 0x74, 0xdf, 0x5d, 0xce, 0x7c, 0xf7, 0x6a, 0xe6, 0xbb, 0xff, 0x66, 0xbe, 0xfb,
	0x73, 0xee, 0x3b, 0x57, 0x73, 0xdf, 0xf9, 0x3b, 0xf7, 0x9d, 0x4f, 0x2f, 0xaf, 0xdf, 0xc6, 0xc5,
	0x8d, 0xd7, 0xa1, 0x27, 0x39, 0x53, 0xfd, 0x66, 0xf5, 0x49, 0xbf, 0xfd, 0x1f, 0x00, 0x00, 0xff,
	0xff, 0xb7, 0x94, 0x87, 0xab, 0x41, 0x03, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LockTokensPacketSent {
		i--
		if m.LockTokensPacketSent {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if m.JoinSwapExactAmountInPacketSent {
		i--
		if m.JoinSwapExactAmountInPacketSent {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if len(m.IcaConnectionId) > 0 {
		i -= len(m.IcaConnectionId)
		copy(dAtA[i:], m.IcaConnectionId)
		i = encodeVarintParams(dAtA, i, uint64(len(m.IcaConnectionId)))
		i--
		dAtA[i] = 0x3a
	}
	if m.DepositLastTime != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DepositLastTime))
		i--
		dAtA[i] = 0x30
	}
	{
		size, err := m.CurrentLiquidityAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.LiquidityDenom) > 0 {
		i -= len(m.LiquidityDenom)
		copy(dAtA[i:], m.LiquidityDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.LiquidityDenom)))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.CurrentDepositAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.DepositDenom) > 0 {
		i -= len(m.DepositDenom)
		copy(dAtA[i:], m.DepositDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DepositDenom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AdminAccount) > 0 {
		i -= len(m.AdminAccount)
		copy(dAtA[i:], m.AdminAccount)
		i = encodeVarintParams(dAtA, i, uint64(len(m.AdminAccount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AdminAccount)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.DepositDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.CurrentDepositAmount.Size()
	n += 1 + l + sovParams(uint64(l))
	l = len(m.LiquidityDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.CurrentLiquidityAmount.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.DepositLastTime != 0 {
		n += 1 + sovParams(uint64(m.DepositLastTime))
	}
	l = len(m.IcaConnectionId)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.JoinSwapExactAmountInPacketSent {
		n += 2
	}
	if m.LockTokensPacketSent {
		n += 2
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdminAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AdminAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentDepositAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CurrentDepositAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidityDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidityDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentLiquidityAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CurrentLiquidityAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositLastTime", wireType)
			}
			m.DepositLastTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositLastTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IcaConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IcaConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JoinSwapExactAmountInPacketSent", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.JoinSwapExactAmountInPacketSent = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockTokensPacketSent", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LockTokensPacketSent = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
